services:
  cloudhub:
    container_name: cloudhub
    image: ghcr.io/shengqiangdd/cloudhub:latest
    network_mode: host
    volumes:
      - cloudhub-data:/data
    restart: "no"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/data/cloudhub.db
      - JWT_SECRET=9c42491a5e21e47ab4b46c5b81096b058882248d98b51095e7285358e53d8258
      - FRONTEND_DIST=/app/working/workspaces/default/cloudhub/frontend/dist
      - PLUGINS_DIR=/app/working/workspaces/default/cloudhub/plugins

volumes:
  cloudhub-data:
